export PG_HOST="localhost"
export PG_PORT="5432"
export PG_ADMIN_USER="postrges"
export PGPASSWORD="xxxxx"
export AWS_ACCESS_KEY="xxxxx"
export AWS_SECRET_KEY="xxxxx"
export AWS_DEFAULT_REGION="ap-south-1"
export BUCKET_NAME="bucket/path"